# Generated by Django 5.0.3 on 2024-07-17 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='create_At',
            new_name='created_At',
        ),
    ]
